# This profile uses the docker-compose DNS names and is activated for the default docker-compose build

spring:
  rabbitmq:
    host: mls-amqp
    username: mls-rabbitmq-user
    password: mls-rabbitmq-pass
  datasource:
    url: jdbc:postgresql://mls-db:5432/mls-coceso?stringtype=unspecified
    driver-class-name: org.postgresql.Driver
    username: mls-coceso
    password: mls-coceso-password
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc:
          lob.non_contextual_creation: true
          time_zone: UTC

application:
  auth:
    verification:
      signing-key: file:/config/dev.pub

logging:
  config: /config/log-docker.xml
  level:
    root: warn
    at.wrk.coceso: debug
