# This profile uses the docker-compose DNS names and is activated for the default docker-compose build

spring:
  rabbitmq:
    host: mls-amqp
    username: mls-rabbitmq-user
    password: mls-rabbitmq-pass
  datasource:
    url: jdbc:postgresql://mls-db:5432/mls-coceso?stringtype=unspecified
    driver-class-name: org.postgresql.Driver
    username: mls-coceso
    password: mls-coceso-password
  jpa:
    hibernate:
      ddl-auto: update

application:
  auth:
    verification:
      signing-key: file:/config/dev.pub
  broker:
    host: mls-amqp
    username: mls-rabbitmq-user
    password: mls-rabbitmq-pass
  messages:
    templates:
      alarm: |
        CCS{{incidentId}}: {{type}}
        BO: {{bo}}
        {{info}}
        Einheiten: {{units}}
        BO URL: {{boUrl}}
      casus: |
        CCS{{incidentId}}
        AO: {{ao}}
        Casus: {{casusNr}} {{erType}}
        AO URL: {{aoUrl}}
    channels:
      - id: /dev/ttyUSB50
        name: Test Port 1
      - id: /dev/ttyUSB51
        name: Test Port 2

logging:
  config: /config/log-docker.xml
  level:
    root: warn
    at.wrk.coceso: debug
